import { Reviewimg } from "../assets";

const PopularCourseslib = [
  {
    img: Reviewimg,
    message:
      "This course will take you through the basics and fundamentals of data analytics.",
    views: "122",
    Videotime: "1hr 25mins",
    time: "12 weeks long",
    category: "Data Analystics",
    rating: "4.8",
    price: "65.5",
  },
  {
    img: Reviewimg,
    message: "message message message1",
    views: "122",
    Videotime: "1hr 25mins",
    time: "12 weeks long",
    category: "Data Analystics",
    rating: "4.8",
    price: "65.5",
  },
  {
    img: Reviewimg,
    message: "message message message2",
    views: "122",
    Videotime: "1hr 25mins",
    time: "12 weeks long",
    category: "Data Analystics",
    rating: "4.8",
    price: "65.5",
  },
  {
    img: Reviewimg,
    message: "message message message3",
    views: "122",
    Videotime: "1hr 25mins",
    time: "12 weeks long",
    category: "Data Analystics",
    rating: "4.8",
    price: "65.5",
  },
  {
    img: Reviewimg,
    message: "message message message4",
    views: "122",
    Videotime: "1hr 25mins",
    time: "12 weeks long",
    category: "Data Analystics",
    rating: "4.8",
    price: "65.5",
  },
  {
    img: Reviewimg,
    message: "message message message5",
    views: "122",
    Videotime: "1hr 25mins",
    time: "12 weeks long",
    category: "Data Analystics",
    rating: "4.8",
    price: "65.5",
  },
  {
    img: Reviewimg,
    message: "message message message6",
    views: "122",
    Videotime: "1hr 25mins",
    time: "12 weeks long",
    category: "Data Analystics",
    rating: "4.8",
    price: "65.5",
  },
  {
    img: Reviewimg,
    message: "message message message7",
    views: "122",
    Videotime: "1hr 25mins",
    time: "12 weeks long",
    category: "Data Analystics",
    rating: "4.8",
    price: "65.5",
  },
];

export default PopularCourseslib;
