import {
  testimonial1,
  testimonial10,
  testimonial11,
  testimonial12,
  testimonial13,
  testimonial14,
  testimonial15,
  testimonial16,
  testimonial17,
  testimonial18,
  testimonial2,
  testimonial3,
  testimonial4,
  testimonial5,
  testimonial6,
  testimonial7,
  testimonial8,
  testimonial9,
} from "../assets";
const Testimonials = [
  { image: testimonial1 },
  { image: testimonial2 },
  { image: testimonial3 },
  { image: testimonial4 },
  { image: testimonial5 },
  { image: testimonial6 },
  { image: testimonial7 },
  { image: testimonial8 },
  { image: testimonial9 },
  { image: testimonial11 },
  { image: testimonial10 },
  { image: testimonial12 },
  { image: testimonial13 },
  { image: testimonial14 },
  { image: testimonial15 },
  { image: testimonial16 },
  { image: testimonial17 },
  { image: testimonial18 },
];

export default Testimonials;
