name: Deploy React to cPanel via FTP

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout the latest code

      - name: Install dependencies
        run: npm install # Install project dependencies

      - name: Build the app
        run: npm run build # Build the React app

      - name: Install lftp
        run: sudo apt-get install lftp # Install lftp for FTPS support

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ziontechub.com # FTP Server Address (or use the IP address directly if DNS is an issue)
          username: ${{ secrets.FTP_USERNAME }} # FTP Username
          password: ${{ secrets.FTP_PASSWORD }} # FTP Password
          local-dir: dist/ # Local build directory
          server-dir: public_html # Destination directory on the FTP server
          protocol: ftp # Use "ftp" for FTP (or "ftps" for FTPS)
